import type { IconType } from 'react-icons'
import {
  FaArrowsSpin,
  FaChartLine,
  FaArrowTrendUp,
  FaNetworkWired,
  FaMicrochip,
  FaServer,
  FaCoins,
  FaMemory,
  FaLocationDot,
  FaRightLeft,
  FaLayerGroup,
  FaBolt,
  FaArrowsRotate,
  FaArrowDownWideShort,
  FaHandshake,
  FaTruckFast,
  FaPaperPlane,
  FaBriefcase,
  FaEarthAmericas,
  FaLandmark,
  FaMedal,
  FaSquareRootVariable,
  FaDivide,
  FaSuperscript,
  FaWindows,
  FaGlobe,
  FaScroll,
  FaFlask,
  FaBookOpen,
  FaBrain,
  FaEye,
  FaBullseye,
  FaComments,
  FaRobot,
  FaDna,
  FaScaleBalanced,
  FaSitemap,
  FaMagnifyingGlassChart,
  FaLightbulb,
  FaSeedling,
} from 'react-icons/fa6'
import {
  TbRoute,
  TbRouter,
  TbBinaryTree,
  TbMathFunction,
  TbMathIntegral,
  TbMath,
  TbChartDots,
  TbColumns3,
} from 'react-icons/tb'
import {
  SiCss3,
  SiDocker,
  SiGit,
  SiJavascript,
  SiNextdotjs,
  SiPython,
  SiReact,
  SiLinux,
  SiTypescript,
} from 'react-icons/si'
import { GiDinosaurRex } from 'react-icons/gi'

const ICON_BY_NAME: Record<string, IconType> = {
  book: FaBookOpen,
  brain: FaBrain,
  network: FaNetworkWired,
  microchip: FaMicrochip,
  server: FaServer,
  route: TbRoute,
  router: TbRouter,
  coins: FaCoins,
  memory: FaMemory,
  location: FaLocationDot,
  binary_tree: TbBinaryTree,
  array: TbColumns3,
  swap: FaRightLeft,
  layers: FaLayerGroup,
  bolt: FaBolt,
  rotate: FaArrowsRotate,
  sort: FaArrowDownWideShort,
  handshake: FaHandshake,
  truck: FaTruckFast,
  paper_plane: FaPaperPlane,
  briefcase: FaBriefcase,
  globe: FaGlobe,
  earth: FaEarthAmericas,
  scroll: FaScroll,
  landmark: FaLandmark,
  medal: FaMedal,
  square_root: FaSquareRootVariable,
  math_function: TbMathFunction,
  math_integral: TbMathIntegral,
  math: TbMath,
  divide: FaDivide,
  superscript: FaSuperscript,
  recurrence: FaArrowsSpin,
  chart_line: FaChartLine,
  trend_up: FaArrowTrendUp,
  chart_dots: TbChartDots,
  magnifying_chart: FaMagnifyingGlassChart,
  sitemap: FaSitemap,
  eye: FaEye,
  bullseye: FaBullseye,
  comments: FaComments,
  robot: FaRobot,
  dna: FaDna,
  scale: FaScaleBalanced,
  lightbulb: FaLightbulb,
  flask: FaFlask,
  plant: FaSeedling,
  dinosaur: GiDinosaurRex,
  css: SiCss3,
  docker: SiDocker,
  git: SiGit,
  javascript: SiJavascript,
  nextjs: SiNextdotjs,
  python: SiPython,
  react: SiReact,
  linux: SiLinux,
  windows: FaWindows,
  typescript: SiTypescript,
}

const ICON_BY_CATEGORY: Record<string, IconType> = {
  computer_science: FaMicrochip,
  mathematics: TbMath,
  history: FaScroll,
  sciences: FaFlask,
  general: FaEarthAmericas,
}

export function getQuizIcon(icon?: string, category?: string): IconType {
  return (
    (icon ? ICON_BY_NAME[icon] : undefined) ??
    (category ? ICON_BY_CATEGORY[category] : undefined) ??
    FaBookOpen
  )
}

export const ICON_NAMES = Object.keys(ICON_BY_NAME)
