import type { IconType } from 'react-icons'
import {
  FaArrowsSpin,
  FaChartLine,
  FaArrowTrendUp,
  FaNetworkWired,
  FaMicrochip,
  FaServer,
  FaCoins,
  FaMemory,
  FaLocationDot,
  FaRightLeft,
  FaLayerGroup,
  FaBolt,
  FaArrowsRotate,
  FaArrowDownWideShort,
  FaHandshake,
  FaTruckFast,
  FaPaperPlane,
  FaBriefcase,
  FaEarthAmericas,
  FaLandmark,
  FaMedal,
  FaSquareRootVariable,
  FaDivide,
  FaSuperscript,
  FaWindows,
  FaGlobe,
  FaCode,
  FaScroll,
  FaFlask,
  FaBookOpen,
} from 'react-icons/fa6'
import {
  TbRoute,
  TbRouter,
  TbBinaryTree,
  TbMathFunction,
  TbMathIntegral,
  TbMath,
} from 'react-icons/tb'
import {
  SiCss3,
  SiDocker,
  SiGit,
  SiJavascript,
  SiNextdotjs,
  SiPython,
  SiReact,
  SiLinux,
  SiTypescript,
} from 'react-icons/si'
import { GiDinosaurRex } from 'react-icons/gi'

const ICON_BY_ID: Record<string, IconType> = {
  'algorithmic-recurrence': FaArrowsSpin,
  'analysis-of-algorithms': FaChartLine,
  'asymptotic-analysis': FaArrowTrendUp,
  'computer-networks': FaNetworkWired,
  'computer-networks2': FaNetworkWired,
  'computer-networks3': FaNetworkWired,
  'datapath-microarchitecture': FaMicrochip,
  'dhcp-protocol': FaServer,
  'dijkstra-algorithm': TbRoute,
  'greedy-algorithms': FaCoins,
  'ijvm-memory-model': FaMemory,
  'ip-addresses': FaLocationDot,
  'minimum-spanning-tree': TbBinaryTree,
  'nat-networks': FaRightLeft,
  'network-layer': FaLayerGroup,
  quic: FaBolt,
  'reliable-data-transfer': FaArrowsRotate,
  'router-data-plane': TbRouter,
  'sorting-algorithms': FaArrowDownWideShort,
  'sorting-algorithms2': FaArrowDownWideShort,
  'sorting-algorithms3': FaArrowDownWideShort,
  tcp: FaHandshake,
  'transport-layer': FaTruckFast,
  udp: FaPaperPlane,
  bmc: FaBriefcase,
  general1: FaEarthAmericas,
  general2: FaEarthAmericas,
  general3: FaEarthAmericas,
  general4: FaEarthAmericas,
  'american-history-1': FaScroll,
  'ancient-greece': FaLandmark,
  wwi: FaMedal,
  wwii: FaMedal,
  'algebraic-processing': FaSquareRootVariable,
  'calculus-derivatives': TbMathFunction,
  'calculus-integrals': TbMathIntegral,
  'fraction-rules': FaDivide,
  'power-rules': FaSuperscript,
  css: SiCss3,
  docker: SiDocker,
  git: SiGit,
  git2: SiGit,
  javascript: SiJavascript,
  javascript2: SiJavascript,
  javascript3: SiJavascript,
  nextjs: SiNextdotjs,
  python: SiPython,
  react: SiReact,
  react2: SiReact,
  'terminal-linux': SiLinux,
  'terminal-windows': FaWindows,
  typescript: SiTypescript,
  typescript2: SiTypescript,
  web1: FaGlobe,
  web2: FaGlobe,
  web3: FaGlobe,
  dinosaurs: GiDinosaurRex,
  dinosaurs2: GiDinosaurRex,
  dinosaurs3: GiDinosaurRex,
}

const ICON_BY_CATEGORY: Record<string, IconType> = {
  Computing: FaMicrochip,
  Programming: FaCode,
  Math: TbMath,
  History: FaScroll,
  Science: FaFlask,
  General: FaEarthAmericas,
}

export function getQuizIcon(id: string, category?: string): IconType {
  return ICON_BY_ID[id] ?? (category ? ICON_BY_CATEGORY[category] : undefined) ?? FaBookOpen
}
